import type { DataEntry } from '@/types'

/**
 * Seed-записи с правильными categoryId/subcategoryId из профилей.
 * npk, rti = fuel; ts94 = trade; ofptk = retail
 */
export const mockEntries: DataEntry[] = [
  {
    id: '1',
    title: 'ТТН №245 от 25.02.2026',
    categoryId: 'primary',
    subcategoryId: 'ttn',
    docTypeId: 'ttn-gsm',
    companyId: 'npk',
    status: 'new',
    docPurpose: 'accounting',
    syncStatus: 'not_applicable',
    source: 'upload',
    sourceLabel: 'Загрузка',
    fileUrl: '/mock/ttn-245.pdf',
    fileType: 'application/pdf',
    fileSize: 245000,
    metadata: { docNumber: '245', docDate: '2026-02-25', counterparty: 'ООО ЛукОйл' },
    createdAt: '2026-02-25T14:32:00Z',
    updatedAt: '2026-02-25T14:32:00Z',
  },
  {
    id: '2',
    title: 'Акт сверки за январь 2026',
    categoryId: 'primary',
    subcategoryId: 'acts',
    docTypeId: 'act-reconciliation',
    companyId: 'npk',
    status: 'recognized',
    docPurpose: 'accounting',
    syncStatus: 'not_applicable',
    source: 'photo',
    sourceLabel: 'Фото',
    fileType: 'image/jpeg',
    fileSize: 1200000,
    metadata: { period: 'Январь 2026', counterparty: 'ИП Петров' },
    createdAt: '2026-02-25T14:15:00Z',
    updatedAt: '2026-02-25T14:20:00Z',
  },
  {
    id: '3',
    title: 'Договор поставки №18',
    categoryId: 'primary',
    subcategoryId: 'contracts',
    docTypeId: 'contract',
    companyId: 'rti',
    status: 'verified',
    docPurpose: 'reference',
    syncStatus: 'not_applicable',
    source: 'upload',
    sourceLabel: 'Загрузка',
    fileType: 'application/pdf',
    fileSize: 520000,
    metadata: { docNumber: '18', docDate: '2026-01-15', counterparty: 'АО Роснефть' },
    createdAt: '2026-02-24T13:50:00Z',
    updatedAt: '2026-02-25T10:00:00Z',
  },
  {
    id: '4',
    title: 'Счёт-фактура №128',
    categoryId: 'primary',
    subcategoryId: 'invoices',
    docTypeId: 'invoice-factura',
    companyId: 'ts94',
    status: 'transferred',
    docPurpose: 'accounting',
    syncStatus: 'pending',
    source: 'api',
    sourceLabel: '1C API',
    fileType: 'application/pdf',
    fileSize: 98000,
    metadata: { docNumber: '128', docDate: '2026-02-20', amount: '458 200 ₽' },
    createdAt: '2026-02-25T13:22:00Z',
    updatedAt: '2026-02-25T13:25:00Z',
  },
  {
    id: '5',
    title: 'Накладная ГСМ февраль',
    categoryId: 'operational',
    subcategoryId: 'fuel-deliveries',
    docTypeId: 'delivery-record',
    companyId: 'npk',
    status: 'error',
    docPurpose: 'accounting',
    syncStatus: 'not_applicable',
    source: 'upload',
    sourceLabel: 'Загрузка',
    fileType: 'text/csv',
    fileSize: 45000,
    metadata: { period: 'Февраль 2026' },
    createdAt: '2026-02-25T12:45:00Z',
    updatedAt: '2026-02-25T12:46:00Z',
  },
  {
    id: '6',
    title: 'Фото чека АЗС №12',
    categoryId: 'media',
    subcategoryId: 'photos',
    docTypeId: 'photo',
    companyId: 'npk',
    status: 'new',
    docPurpose: 'context',
    syncStatus: 'not_applicable',
    source: 'photo',
    sourceLabel: 'Фото',
    fileType: 'image/jpeg',
    fileSize: 3400000,
    metadata: { azs: 'АЗС №12', date: '2026-02-25' },
    createdAt: '2026-02-25T12:10:00Z',
    updatedAt: '2026-02-25T12:10:00Z',
  },
  {
    id: '7',
    title: 'Реестр платежей за неделю',
    categoryId: 'financial',
    subcategoryId: 'reconciliation',
    docTypeId: 'financial-report',
    companyId: 'rti',
    status: 'verified',
    docPurpose: 'accounting',
    syncStatus: 'confirmed',
    source: 'manual',
    sourceLabel: 'Ручной',
    metadata: { period: '17-23 февраля 2026', count: '45 записей' },
    createdAt: '2026-02-25T11:30:00Z',
    updatedAt: '2026-02-25T14:00:00Z',
  },
  {
    id: '8',
    title: 'Приходная накладная №34',
    categoryId: 'primary',
    subcategoryId: 'supply',
    docTypeId: 'supply-invoice',
    companyId: 'ofptk',
    status: 'new',
    docPurpose: 'accounting',
    syncStatus: 'not_applicable',
    source: 'upload',
    sourceLabel: 'Загрузка',
    fileType: 'application/pdf',
    fileSize: 180000,
    metadata: { docNumber: '34', docDate: '2026-02-24' },
    createdAt: '2026-02-24T16:00:00Z',
    updatedAt: '2026-02-24T16:00:00Z',
  },
  {
    id: '9',
    title: 'Счёт на оплату №56',
    categoryId: 'primary',
    subcategoryId: 'invoices',
    docTypeId: 'invoice',
    companyId: 'ts94',
    status: 'recognized',
    docPurpose: 'accounting',
    syncStatus: 'not_applicable',
    source: 'photo',
    sourceLabel: 'Фото',
    fileType: 'image/png',
    fileSize: 890000,
    metadata: { docNumber: '56', amount: '125 000 ₽' },
    createdAt: '2026-02-24T15:00:00Z',
    updatedAt: '2026-02-24T15:10:00Z',
  },
  {
    id: '10',
    title: 'Остатки топлива 25.02',
    categoryId: 'operational',
    subcategoryId: 'inventory',
    docTypeId: 'fuel-inventory',
    companyId: 'npk',
    status: 'verified',
    docPurpose: 'accounting',
    syncStatus: 'exported',
    source: 'api',
    sourceLabel: 'API процессинг',
    metadata: { date: '2026-02-25', ai92: '12500 л', ai95: '8200 л', dt: '15400 л' },
    createdAt: '2026-02-25T08:00:00Z',
    updatedAt: '2026-02-25T08:05:00Z',
  },
]
